"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"


format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$hostname\
$container\
$character"""

right_format = """
$status\
$nodejs\
$python\
$php\
$terraform\
$aws\
$cmd_duration"""

command_timeout = 1000

# [character]
# Note the use of Catppuccin color 'peach'
# success_symbol = "[[󰄛](green) ❯](green)"
# error_symbol = "[[󰄛](red) ❯](red)"
# vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[directory]
style = "bold lavender"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[aws]
symbol = " "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[c]
disabled = true
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[daml]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[dart]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[deno]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[dotnet]
disabled = true
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
disabled = true
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[erlang]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[fennel]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
disabled = true
format = '\[[$symbol$branch]($style)\]'

[gcloud]
disabled = true
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = " "
style = "bold mauve"
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[gradle]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
disabled = true
format = '\[[$symbol]($style)\]'

[haskell]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[haxe]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[helm]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
disabled = true
format = '\[[$symbol$branch]($style)\]'

[hostname]
ssh_symbol = " "

[java]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[julia]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[kotlin]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
disabled = true
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
disabled = true
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
disabled = true
format = '\[[$symbol$project]($style)\]'

[nim]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
disabled = true
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[ocaml]
disabled = true
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[openstack]
disabled = true
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
disabled = true
format = '\[[$symbol]($style)\]'

[package]
disabled = true
format = '\[[$symbol$version]($style)\]'

[perl]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
disabled = true
format = '\[[$symbol$channel]($style)\]'

[pulumi]
disabled = true
format = '\[[$symbol$stack]($style)\]'

[purescript]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
disabled = true
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[ruby]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[rust]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[scala]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[spack]
disabled = true
format = '\[[$symbol$environment]($style)\]'

# ~/.config/starship.toml

[status]
# style = 'bg:blue'
symbol = '✘ '
success_symbol = ''
not_executable_symbol = '󰅙 '
not_found_symbol = '󰦀 '
sigint_symbol = ''
signal_symbol = '󰅛 '
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[terraform]
symbol = "󱁢 "
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[vlang]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[zig]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[solidity]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
